export enum ENUM_DELIVERY_ZONE {
    INSIDE_DHAKA = 'INSIDE_DHAKA',
    NEARBY_DHAKA = 'NEARBY_DHAKA',
    OUTSIDE_DHAKA = 'OUTSIDE_DHAKA'
}

export enum ENUM_DELIVERY_URGENCY {
    REGULAR = 'REGULAR',
    EXPRESS = 'EXPRESS',
}

export enum ENUM_PANEL {
    WEB = 'WEB',
    PANEL = 'PANEL',
}

export enum ENUM_PRIORITY {
    REGULAR = 'REGULAR',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
}

export enum ENUM_ORDER_SOURCE {
    WEBSITE = 'WEBSITE',
    APP = 'APP',
    FACEBOOK = 'FACEBOOK',
    INSTAGRAM = 'INSTAGRAM',
    WHATSAPP = 'WHATSAPP',
    CALL = 'CALL',
}

export enum ENUM_DISCOUNT_TYPE {
    MEMBERSHIP = 'MEMBERSHIP',
    COUPON = 'COUPON',
    CAMPAIGN = 'CAMPAIGN',
}

export enum ENUM_ORDER_PAYMENT_STATUS {
    UNPAID = 'UNPAID',
    PAID = 'PAID',
    PARTIALLY_PAID = 'PARTIALLY_PAID',
    DELIVERY_CHARGE_PAID = 'DELIVERY_CHARGE_PAID',
}

export enum ENUM_INTERNAL_ORDER_STATUS {
    PENDING = 'PENDING',
    CONFIRMED = 'CONFIRMED',
    SOURCING = 'SOURCING',
    PACKAGING = 'PACKAGING',
    READY_TO_SHIP = 'READY_TO_SHIP',
    PICKED_FOR_DELIVERY = 'PICKED_FOR_DELIVERY',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    RETURN_REQUESTED = 'RETURN_REQUESTED',
    RETURNED = 'RETURNED',
    CANCELLED = 'CANCELLED',
    REFUNDED = 'REFUNDED',
    EXCHANGE_REQUESTED = 'EXCHANGE_REQUESTED',
    EXCHANGED = 'EXCHANGED',
    HOLD = 'HOLD',
}

export enum ENUM_CUSTOMER_ORDER_STATUS {
    PENDING = 'PENDING',
    CONFIRMED = 'CONFIRMED',
    PROCESSING = 'PROCESSING',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    RETURNED = 'RETURNED',
    CANCELLED = 'CANCELLED',
}

// Allowed transitions (directed graph)
export const ORDER_FLOW: Record<ENUM_INTERNAL_ORDER_STATUS, ENUM_INTERNAL_ORDER_STATUS[]> = {
    [ENUM_INTERNAL_ORDER_STATUS.PENDING]: [ENUM_INTERNAL_ORDER_STATUS.CONFIRMED, ENUM_INTERNAL_ORDER_STATUS.CANCELLED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.CONFIRMED]: [ENUM_INTERNAL_ORDER_STATUS.SOURCING, ENUM_INTERNAL_ORDER_STATUS.CANCELLED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.SOURCING]: [ENUM_INTERNAL_ORDER_STATUS.PACKAGING, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.PACKAGING]: [ENUM_INTERNAL_ORDER_STATUS.READY_TO_SHIP, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.READY_TO_SHIP]: [ENUM_INTERNAL_ORDER_STATUS.PICKED_FOR_DELIVERY, ENUM_INTERNAL_ORDER_STATUS.OUT_FOR_DELIVERY, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.PICKED_FOR_DELIVERY]: [ENUM_INTERNAL_ORDER_STATUS.OUT_FOR_DELIVERY, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.OUT_FOR_DELIVERY]: [ENUM_INTERNAL_ORDER_STATUS.DELIVERED, ENUM_INTERNAL_ORDER_STATUS.RETURNED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.DELIVERED]: [ENUM_INTERNAL_ORDER_STATUS.RETURN_REQUESTED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.RETURN_REQUESTED]: [ENUM_INTERNAL_ORDER_STATUS.RETURNED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.RETURNED]: [ENUM_INTERNAL_ORDER_STATUS.EXCHANGE_REQUESTED, ENUM_INTERNAL_ORDER_STATUS.REFUNDED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.EXCHANGE_REQUESTED]: [ENUM_INTERNAL_ORDER_STATUS.EXCHANGED, ENUM_INTERNAL_ORDER_STATUS.HOLD],
    [ENUM_INTERNAL_ORDER_STATUS.HOLD]: [ENUM_INTERNAL_ORDER_STATUS.CONFIRMED, ENUM_INTERNAL_ORDER_STATUS.SOURCING, ENUM_INTERNAL_ORDER_STATUS.PACKAGING, ENUM_INTERNAL_ORDER_STATUS.READY_TO_SHIP, ENUM_INTERNAL_ORDER_STATUS.PICKED_FOR_DELIVERY, ENUM_INTERNAL_ORDER_STATUS.OUT_FOR_DELIVERY, ENUM_INTERNAL_ORDER_STATUS.DELIVERED, ENUM_INTERNAL_ORDER_STATUS.RETURN_REQUESTED, ENUM_INTERNAL_ORDER_STATUS.RETURNED, ENUM_INTERNAL_ORDER_STATUS.EXCHANGE_REQUESTED, ENUM_INTERNAL_ORDER_STATUS.CANCELLED, ENUM_INTERNAL_ORDER_STATUS.REFUNDED, ENUM_INTERNAL_ORDER_STATUS.EXCHANGED],
    [ENUM_INTERNAL_ORDER_STATUS.CANCELLED]: [],
    [ENUM_INTERNAL_ORDER_STATUS.REFUNDED]: [],
    [ENUM_INTERNAL_ORDER_STATUS.EXCHANGED]: []
};

export interface IOrderAddress {
    id: string,
    label: string,
    fullName: string,
    phoneNumber: string,
    email: string,
    isThisWhatsAppNumber: boolean,
    addressLine1: string,
    addressLine2: string,
    areaId: string,
    areaTitle: string,
    // cityId: null,
    // cityTitle: null,
    deliveryChargeId: string,
    deliveryCharge: number,
    deliveryZone: string,
}