export enum ENUM_PAYMENT_METHOD {
  CASH = 'CASH',
  CARD = 'CARD',
  BFTN = 'BFTN',
  BKASH = 'BKASH',
  NAGAD = 'NAGAD',
  CASH_CHEQUE = 'CASH_CHEQUE',
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  ACCOUNT_PAYEE_CHEQUE = 'ACCOUNT_PAYEE_CHEQUE',
}

export enum ENUM_PAYMENT_METHOD_CATEGORY {
  UNKNOWN = 'UNKNOWN',
  CASH = 'CASH',
  CARD = 'CARD',
  MOBILE_BANKING = 'MOBILE_BANKING',
  BANK_TRANSFER = 'BANK_TRANSFER',
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  BANK_CHEQUE = 'BANK_CHEQUE',
}

export enum ENUM_TRANSACTION_STATUS {
  PENDING = 'pending',
  SUCCESS = 'success',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  HOLD = 'hold',
}
