export enum ENUM_OFFER_TAG {
  FLASH_SALE = 'FLASH_SALE',
  CLEARANCE = 'CLEARANCE',
  EID = 'EID',
  SEASONAL = 'SEASONAL',
  CUSTOM = 'CUSTOM',
}

export enum ENUM_DISCOUNT_TYPE {
  FLAT = 'FLAT',
  PERCENTAGE = 'PERCENTAGE',
  BOGO = 'BOGO',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
  BUY_X_GET_PCT = 'BUY_X_GET_PCT',
}

export enum ENUM_SCOPE_TYPE {
  ALL_PRODUCTS = 'ALL_PRODUCTS',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
  VARIANT = 'VARIANT',
}
