name: Fibonaccibooks Production CD

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate .env
        run: |
          envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./environments/example.env > ./environments/$NODE_ENV.env
        env:
          PORT: 5000
          NODE_ENV: production
          APP_IDENTIFIER: fibonacci-production
          APP_TITLE: Fibonacci
          API_PREFIX: api/v1
          TZ: UTC

          # Swagger
          API_VERSION: 1.0.0
          API_TITLE: Fibonacci Book & Such API PRODUCTION
          API_DESCRIPTION: Fibonacci Book & Such API PRODUCTION

          # Default DB
          DB_TYPE: postgres
          DB_HOST: ${{ secrets.PRODUCTION_HOST }}
          DB_PORT: 5432
          DB_USERNAME: ${{ secrets.PRODUCTION_POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.PRODUCTION_POSTGRES_PASS }}
          DB_DATABASE: secure-fibonacci-books_db
          DB_SYNCHRONIZE: true
          DB_LOGGING: false

          # Security
          CORS_ALLOWED_ORIGINS: https://api.fibonaccibookshop.com,https://panel.fibonaccibookshop.com,https://beta.fibonaccibookshop.com,https://fibonaccibookshop.com,https://www.fibonaccibookshop.com
          RATE_LIMIT_TTL: 60000
          RATE_LIMIT_MAX: 100

          # Logger
          LOG_FOLDER: logs

          # JWT
          JWT_SECRET: ssh-rsa AAAAB3NzaC1yc2EAAAdwADAQABAAwdwwABAQfC8kf3x3Wi9V3kMkYu9tjDwdwaSRD2cBjOgp3FQwdwU/Gndlced9WsaVNx3lgkbbS47sPpFMdQVSgemGbRqhaj9vUrD56+QOMn5HuxeAp5VMwwD$
          JWT_SALT_ROUNDS: 10
          JWT_EXPIRES_IN: 10d
          JWT_REFRESH_TOKEN_EXPIRES_IN: 30d

          # Auth
          OTP_EXPIRES_IN: 5000

          WEB_PANEL_LOGIN_LINK: https://fibonaccibookshop.com/auth
          INTERNAL_PANEL_LOGIN_LINK: https://panel.fibonaccibookshop.com/auth

          # Seed Database
          SUPER_ADMIN_EMAIL: superadmin@fibonaccibookshop.com
          SUPER_ADMIN_PASSWORD: boss@FIBO

          #QUEUE
          QUEUE_HOST: redis
          QUEUE_PORT: 6379
          QUEUE_PASSWORD: 'PiTech.domanaged#redis'

          # Cache
          CACHE_API_DATA: false
          CACHE_TTL: 60
          CACHE_MAX: 100
          CACHE_STORE_HOST: redis
          CACHE_STORE_PORT: 6379
          CACHE_STORE_PASSWORD: 'PiTech.domanaged#redis'
          CACHE_STORE_USERNAME: default

          #SMTP
          SMTP_HOST: smtp-relay.brevo.com
          SMTP_PORT: 2525
          SMTP_SECURE: false
          SMTP_AUTH_USER: 7b8634001@smtp-brevo.com
          SMTP_AUTH_PASS: r4HCV8GL7ywhP9BX
          SMTP_EMAIL: hello@fibonaccibookshop.com

          BKASH_TOKEN_URL: https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/token/grant
          BKASH_CREATE_URL: https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/create
          BKASH_EXECUTE_URL: https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/execute
          BKASH_PAYMENT_STATUS_URL: https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/payment/status
          BKASH_SEARCH_TRANSACTION_URL: https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/general/searchTransaction
          BKASH_REFUND_TRANSACTION_URL: https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout/payment/refund
          BKASH_APP_KEY: AAZmRLlN81MLwi2PkTC7Cy0Ttc
          BKASH_APP_SECRET: e5NIJJwuTstroz6y5mS9uqgkXFkDJWm45bFhpIsp0Pk6dWEw288F
          BKASH_USERNAME: '01749642762'
          BKASH_PASSWORD: '}J,!fH7%PN('
          BKASH_WEB_HOOK_URL: https://api.fibonaccibookshop.com/api/v1/web/payment-gateway-requests/bkash/webhook

          CORE_API_ENDPOINT: https://api.fibonaccibookshop.com/api/v1
          WEB_URL: https://fibonaccibookshop.com

          # SYSTEM CONFIG
          PRODUCT_CODE_PREFIX: FIBO
          MEMBERSHIP_CODE_PREFIX: FIBO
          ODER_INVOICE_TEMPLATE: fibo-order-invoice

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build the project
        run: yarn run build
        env:
          CI: false

      - name: Deploy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_PRIVATE_KEY }}
          rm: true
          source: './' # This will send all files, including the build directory
          target: '/home/pitech/deployed-services/fibo-api-prod/' # This will send all files, including the build directory
          strip_components: 0

  deploy-fibo-api-prod-to-DO:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/pitech/deployed-services/fibo-api-prod/
            echo "calling shutdown endpoint..."
            docker stop fibo-api-prod || true
            docker rm fibo-api-prod || true

            echo "Building the image..."
            docker build -t fibo-api-prod:local -f /home/pitech/deployed-services/fibo-api-prod/Dockerfile.prod .

            echo "starting server instance..."
            docker run -e NODE_ENV=production -d \
              --restart always \
              -dit --name fibo-api-prod --network docker_docker_net \
              -p 0.0.0.0:5000:5000 \
              --name fibo-api-prod \
              -v /home/pitech/deployed-services/fibo-api-prod/dist:/app/dist \
              fibo-api-prod:local

            docker builder prune -f
            docker image prune -f
            echo "Deploy Done...."
